//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon_Proje.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> SATISFIYAT { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<bool> KRITIKSEVIYE { get; set; }
        public Nullable<int> KATEGORI { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLFIRMAHAREKET TBLFIRMAHAREKET { get; set; }
    }
}
